"""
Django settings for website_monitor project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u%_1gkuzv%9m-f3jbgqq7%$d*9w1nf%=twi%ua5&y7(s3a1fbq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# CSRF trusted origins for Replit
CSRF_TRUSTED_ORIGINS = [
    'https://*.replit.dev',
    'https://*.repl.co',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # your apps
    'website_monitor.monitor',
    'django_crontab',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website_monitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website_monitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -------------------------------
# Celery Configuration
# -------------------------------
#CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
#CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
#CELERY_ACCEPT_CONTENT = ['json']
#CELERY_TASK_SERIALIZER = 'json'
#CELERY_RESULT_SERIALIZER = 'json'
#CELERY_TIMEZONE = 'Asia/Kolkata'

#from celery.schedules import crontab

# CELERY_BEAT_SCHEDULE = {
  #  'run-monitor-command-every-30-seconds': {
   #     'task': 'monitor.tasks.run_monitor_command',
    #    'schedule': 30.0,  # run every 30 seconds
    #},
#}


# -------------------------------
# Email Configuration (Configurable)
# -------------------------------
# Replace these values before running the project

# ======================================================
# ✅ SiteCareGuard Email-Only Configuration (Final)
# ======================================================

# Use Asia/Kolkata for proper timestamp in logs
TIME_ZONE = 'Asia/Kolkata'

# ------------------------------------------------------
# EMAIL (GMAIL SMTP) CONFIGURATION
# ------------------------------------------------------
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 465
#EMAIL_USE_SSL = True

# ⚠️ Replace with your actual Gmail + App Password
#EMAIL_HOST_USER = 'harikrishnapagilla@gmail.com'
#EMAIL_HOST_PASSWORD = ''   # ✅ this must be your Google App Password
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Optional: recipients list
#ALERT_RECIPIENTS = ['']

# Celery (disabled)
# CELERY_BROKER_URL = ''
# CELERY_RESULT_BACKEND = ''
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =====================
# TWILIO SMS SETTINGS
# =====================
TWILIO_ACCOUNT_SID = ""#enter twillo account sid
TWILIO_AUTH_TOKEN = ""# enter twillo auth token
TWILIO_FROM_NUMBER = "+12314420857"    # your Twilio phone number
ADMIN_PHONE_NUMBER = "+916303462648"   # your personal mobile number

# --- Email configuration placeholders ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'harikrishnapagilla@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')#enter your email password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ALERT_RECIPIENTS = [os.getenv('ALERT_RECIPIENT', EMAIL_HOST_USER)]

# --- Celery / Redis settings ---
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

CELERY_BEAT_SCHEDULE = {
    'run-every-30-seconds': {
        'task': 'website_monitor.monitor.tasks.check_all_websites_task',
        'schedule': 30.0,
    },
}


# ------------------------------------------------------
# CRON JOB CONFIGURATION
# ------------------------------------------------------
CRONJOBS = [
    # Run the website check every minute
    ('* * * * *', 'django.core.management.call_command', ['check_websites']),
]

