# Generated by Django 5.2.8 on 2025-11-08 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the website', max_length=200)),
                ('url', models.URLField(help_text='Full URL to monitor', max_length=500, unique=True)),
                ('check_interval', models.IntegerField(default=300, help_text='Check interval in seconds')),
                ('timeout', models.IntegerField(default=10, help_text='Request timeout in seconds')),
                ('expected_status_code', models.IntegerField(default=200, help_text='Expected HTTP status code')),
                ('current_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
                ('last_response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('down', 'Website Down'), ('up', 'Website Up'), ('degraded', 'Degraded Performance')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('is_up', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='monitor.website')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['website', '-checked_at'], name='monitor_hea_website_702609_idx')],
            },
        ),
    ]
