# Generated by Django 5.2.8 on 2025-11-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthchecklog',
            name='response_time',
            field=models.FloatField(blank=True, help_text='Response time in milliseconds', null=True),
        ),
    ]
