# Generated by Django 5.2.8 on 2025-11-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_healthchecklog_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
