# Generated by Django 5.2.8 on 2025-11-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alert_alert_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_sent',
        ),
        migrations.AddField(
            model_name='website',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='down_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(default='Up', max_length=20),
        ),
    ]
